# Generated by Django 4.0.6 on 2022-07-13 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='timr_update',
            new_name='time_update',
        ),
    ]
